[vms]
vm1 ansible_host=127.0.0.1 ansible_port=2221

vm2 ansible_host=172.20.0.20 ansible_ssh_common_args='-o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o ProxyCommand="ssh -i /home/soura/.ssh/v7_ansible -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -p 2221 -W %h:%p ansible_user@127.0.0.1"'

vm3 ansible_host=172.20.0.30 ansible_ssh_common_args='-o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o ProxyCommand="ssh -i /home/soura/.ssh/v7_ansible -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -p 2221 -W %h:%p ansible_user@127.0.0.1"'

[vms:vars]
ansible_user=ansible_user
ansible_ssh_private_key_file=/home/soura/.ssh/v7_ansible
